(clear)
(load "C:\Users\josep\Google Drive\FIB\IA\Lab\Prac2\Code\Practica.pont")
(load-instances "C:\Users\josep\Google Drive\FIB\IA\Lab\Prac2\Code\Practica.pins")
(load "C:\Users\josep\Google Drive\FIB\IA\Lab\Prac2\Code\Practica.clp")
(reset)
